/********************************************************************************
** Form generated from reading UI file 'controlcenter.ui'
**
** Created: Sat Mar 29 16:45:51 2014
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_CONTROLCENTER_H
#define UI_CONTROLCENTER_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QListWidget>
#include <QtGui/QPushButton>
#include <QtGui/QRadioButton>
#include <QtGui/QSpinBox>
#include <QtGui/QTabWidget>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_ControlCenter
{
public:
    QLabel *label;
    QTabWidget *tab1;
    QWidget *tab;
    QListWidget *lw_desc;
    QPushButton *pb_clear;
    QGroupBox *groupBox;
    QLabel *label_4;
    QLineEdit *le_numIfaces;
    QLabel *label_5;
    QSpinBox *sb_selectIf;
    QLabel *label_6;
    QLineEdit *le_numAlt;
    QLabel *label_7;
    QCheckBox *cb_kerneldriver;
    QPushButton *pb_kerneldetach;
    QSpinBox *sb_selectAIf;
    QPushButton *pb_setIFace;
    QFrame *line;
    QPushButton *pb_setAltIf;
    QListWidget *lw_summ;
    QLabel *label_21;
    QWidget *tab_3;
    QTabWidget *tab2;
    QWidget *tab_4;
    QGroupBox *groupBox_2;
    QRadioButton *rb1_ram;
    QRadioButton *rb1_small;
    QRadioButton *rb1_large;
    QPushButton *pb1_selfile;
    QLabel *label_3;
    QLabel *label1_selfile;
    QListWidget *lw1_display;
    QPushButton *pb1_start;
    QPushButton *pb1_clear;
    QGroupBox *groupBox_3;
    QRadioButton *rb_internal;
    QRadioButton *rb_external;
    QWidget *tab_5;
    QListWidget *lw4_display;
    QLabel *label4_file;
    QPushButton *pb4_selfile;
    QPushButton *pb4_start;
    QPushButton *pb4_clear;
    QLabel *label_23;
    QGroupBox *groupBox_5;
    QRadioButton *rb4_ram;
    QRadioButton *rb4_i2c;
    QRadioButton *rb4_spi;
    QWidget *tab_6;
    QGroupBox *groupBox_4;
    QRadioButton *rb3_ramdl;
    QRadioButton *rb3_ramup;
    QRadioButton *rb3_eedl;
    QRadioButton *rb3_eeup;
    QRadioButton *rb3_getchip;
    QRadioButton *rb3_renum;
    QRadioButton *rb3_custom;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLineEdit *le3_br;
    QLineEdit *le3_bm;
    QGroupBox *gb_dir;
    QRadioButton *rb3_out;
    QRadioButton *rb3_in;
    QLineEdit *le3_wval;
    QLineEdit *le3_wind;
    QLineEdit *le3_wlen;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLineEdit *le3_out_hex;
    QPushButton *pb_execvc;
    QPushButton *pb3_selfile;
    QLabel *lab3_selfile;
    QLabel *label_26;
    QPushButton *pb3_dl;
    QListWidget *lw3;
    QPushButton *pb3;
    QLabel *label_22;
    QLineEdit *le3_out_ascii;
    QLabel *label_25;
    QLabel *label_30;
    QWidget *tab_2;
    QTabWidget *tabWidget;
    QWidget *tab_7;
    QComboBox *cb6_out;
    QComboBox *cb6_in;
    QGroupBox *groupBox_6;
    QRadioButton *rb6_constant;
    QRadioButton *rb6_random;
    QRadioButton *rb6_inc;
    QLineEdit *le6_value;
    QLabel *label_27;
    QLineEdit *le6_size;
    QCheckBox *cb6_loop;
    QLabel *label_28;
    QListWidget *lw6;
    QPushButton *pb6_clear;
    QPushButton *pb6_send;
    QPushButton *pb6_rcv;
    QLabel *label_31;
    QLabel *label_32;
    QGroupBox *groupBox_8;
    QLabel *label6_out;
    QLabel *label6_in;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_24;
    QLineEdit *le6_out_ascii;
    QLineEdit *le6_out_hex;
    QLabel *label_37;
    QLabel *label_29;
    QPushButton *pb6_selout;
    QPushButton *pb6_selin;
    QLineEdit *le6_outfile;
    QLineEdit *le6_infile;
    QListWidget *lw6_out;
    QLabel *label_75;
    QPushButton *pb6_clearhalt_out;
    QPushButton *pb6_clearhalt_in;
    QWidget *tab_8;
    QPushButton *pb7_clear;
    QPushButton *pb7_rcv;
    QComboBox *cb7_in;
    QPushButton *pb7_send;
    QComboBox *cb7_out;
    QLabel *label_71;
    QGroupBox *groupBox_16;
    QLabel *label_72;
    QLabel *label_73;
    QLabel *label7_totalout;
    QLabel *label_78;
    QLabel *label_80;
    QLabel *label7_totalin;
    QLabel *label7_rateout;
    QLabel *label7_ratein;
    QLabel *label7_pktsize_out;
    QLabel *label7_pktsize_in;
    QLabel *label_70;
    QFrame *line_2;
    QLabel *label7_pktsin;
    QLabel *label_79;
    QLabel *label7_pktsout;
    QLabel *label_81;
    QLabel *label7_dropped_out;
    QLabel *label7_dropped_in;
    QLabel *label_74;
    QListWidget *lw7_out;
    QListWidget *lw7_in;
    QLabel *label_66;
    QLabel *label_76;
    QLabel *label_77;
    QComboBox *cb7_numpkts;
    QGroupBox *groupBox_7;
    QRadioButton *rb7_enable;
    QRadioButton *rb7_disable;
    QPushButton *pb7_clearhalt_in;
    QPushButton *pb7_clearhalt_out;
    QLabel *label_2;
    QLabel *label_seldevice;
    QListWidget *listWidget;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_if;
    QLabel *label_aif;
    QPushButton *pb_reset;
    QLabel *label_20;
    QLabel *label_devtype;

    void setupUi(QWidget *ControlCenter)
    {
        if (ControlCenter->objectName().isEmpty())
            ControlCenter->setObjectName(QString::fromUtf8("ControlCenter"));
        ControlCenter->setWindowModality(Qt::NonModal);
        ControlCenter->resize(880, 660);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(ControlCenter->sizePolicy().hasHeightForWidth());
        ControlCenter->setSizePolicy(sizePolicy);
        ControlCenter->setMinimumSize(QSize(880, 660));
        ControlCenter->setMaximumSize(QSize(880, 660));
        QFont font;
        font.setFamily(QString::fromUtf8("DejaVu Serif"));
        ControlCenter->setFont(font);
        QIcon icon;
        icon.addFile(QString::fromUtf8("cypress.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon.addFile(QString::fromUtf8("cypress.png"), QSize(), QIcon::Normal, QIcon::On);
        ControlCenter->setWindowIcon(icon);
        label = new QLabel(ControlCenter);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(0, 40, 121, 16));
        tab1 = new QTabWidget(ControlCenter);
        tab1->setObjectName(QString::fromUtf8("tab1"));
        tab1->setGeometry(QRect(0, 165, 871, 476));
        tab1->setTabShape(QTabWidget::Rounded);
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        lw_desc = new QListWidget(tab);
        lw_desc->setObjectName(QString::fromUtf8("lw_desc"));
        lw_desc->setGeometry(QRect(420, 10, 441, 421));
        QFont font1;
        font1.setFamily(QString::fromUtf8("DejaVu Sans Mono"));
        lw_desc->setFont(font1);
        pb_clear = new QPushButton(tab);
        pb_clear->setObjectName(QString::fromUtf8("pb_clear"));
        pb_clear->setGeometry(QRect(360, 10, 51, 31));
        groupBox = new QGroupBox(tab);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 0, 341, 161));
        groupBox->setAutoFillBackground(false);
        groupBox->setFlat(false);
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(11, 21, 91, 16));
        le_numIfaces = new QLineEdit(groupBox);
        le_numIfaces->setObjectName(QString::fromUtf8("le_numIfaces"));
        le_numIfaces->setGeometry(QRect(110, 20, 31, 25));
        le_numIfaces->setReadOnly(true);
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(141, 24, 81, 16));
        sb_selectIf = new QSpinBox(groupBox);
        sb_selectIf->setObjectName(QString::fromUtf8("sb_selectIf"));
        sb_selectIf->setGeometry(QRect(220, 20, 41, 25));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(10, 100, 181, 16));
        le_numAlt = new QLineEdit(groupBox);
        le_numAlt->setObjectName(QString::fromUtf8("le_numAlt"));
        le_numAlt->setGeometry(QRect(200, 100, 31, 25));
        le_numAlt->setReadOnly(true);
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(10, 130, 171, 16));
        cb_kerneldriver = new QCheckBox(groupBox);
        cb_kerneldriver->setObjectName(QString::fromUtf8("cb_kerneldriver"));
        cb_kerneldriver->setEnabled(true);
        cb_kerneldriver->setGeometry(QRect(10, 50, 141, 31));
        cb_kerneldriver->setCheckable(true);
        pb_kerneldetach = new QPushButton(groupBox);
        pb_kerneldetach->setObjectName(QString::fromUtf8("pb_kerneldetach"));
        pb_kerneldetach->setGeometry(QRect(160, 50, 90, 27));
        sb_selectAIf = new QSpinBox(groupBox);
        sb_selectAIf->setObjectName(QString::fromUtf8("sb_selectAIf"));
        sb_selectAIf->setGeometry(QRect(200, 130, 41, 25));
        pb_setIFace = new QPushButton(groupBox);
        pb_setIFace->setObjectName(QString::fromUtf8("pb_setIFace"));
        pb_setIFace->setGeometry(QRect(260, 20, 71, 27));
        line = new QFrame(groupBox);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(10, 80, 311, 20));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        pb_setAltIf = new QPushButton(groupBox);
        pb_setAltIf->setObjectName(QString::fromUtf8("pb_setAltIf"));
        pb_setAltIf->setGeometry(QRect(250, 130, 71, 27));
        lw_summ = new QListWidget(tab);
        lw_summ->setObjectName(QString::fromUtf8("lw_summ"));
        lw_summ->setGeometry(QRect(10, 180, 401, 251));
        lw_summ->setFont(font1);
        label_21 = new QLabel(tab);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 160, 391, 21));
        label_21->setFont(font1);
        tab1->addTab(tab, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QString::fromUtf8("tab_3"));
        tab2 = new QTabWidget(tab_3);
        tab2->setObjectName(QString::fromUtf8("tab2"));
        tab2->setGeometry(QRect(0, 10, 841, 331));
        tab_4 = new QWidget();
        tab_4->setObjectName(QString::fromUtf8("tab_4"));
        groupBox_2 = new QGroupBox(tab_4);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 10, 191, 101));
        rb1_ram = new QRadioButton(groupBox_2);
        rb1_ram->setObjectName(QString::fromUtf8("rb1_ram"));
        rb1_ram->setGeometry(QRect(11, 21, 177, 19));
        rb1_small = new QRadioButton(groupBox_2);
        rb1_small->setObjectName(QString::fromUtf8("rb1_small"));
        rb1_small->setGeometry(QRect(11, 46, 177, 19));
        rb1_large = new QRadioButton(groupBox_2);
        rb1_large->setObjectName(QString::fromUtf8("rb1_large"));
        rb1_large->setGeometry(QRect(11, 71, 177, 19));
        pb1_selfile = new QPushButton(tab_4);
        pb1_selfile->setObjectName(QString::fromUtf8("pb1_selfile"));
        pb1_selfile->setGeometry(QRect(100, 200, 111, 27));
        label_3 = new QLabel(tab_4);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(220, 10, 91, 16));
        label1_selfile = new QLabel(tab_4);
        label1_selfile->setObjectName(QString::fromUtf8("label1_selfile"));
        label1_selfile->setGeometry(QRect(320, 0, 511, 31));
        label1_selfile->setFrameShape(QFrame::Box);
        lw1_display = new QListWidget(tab_4);
        lw1_display->setObjectName(QString::fromUtf8("lw1_display"));
        lw1_display->setGeometry(QRect(220, 40, 611, 251));
        lw1_display->setFont(font1);
        pb1_start = new QPushButton(tab_4);
        pb1_start->setObjectName(QString::fromUtf8("pb1_start"));
        pb1_start->setGeometry(QRect(100, 230, 111, 27));
        pb1_clear = new QPushButton(tab_4);
        pb1_clear->setObjectName(QString::fromUtf8("pb1_clear"));
        pb1_clear->setGeometry(QRect(170, 260, 41, 27));
        groupBox_3 = new QGroupBox(tab_4);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 120, 91, 71));
        rb_internal = new QRadioButton(groupBox_3);
        rb_internal->setObjectName(QString::fromUtf8("rb_internal"));
        rb_internal->setGeometry(QRect(0, 20, 106, 20));
        rb_external = new QRadioButton(groupBox_3);
        rb_external->setObjectName(QString::fromUtf8("rb_external"));
        rb_external->setGeometry(QRect(0, 40, 106, 20));
        tab2->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QString::fromUtf8("tab_5"));
        lw4_display = new QListWidget(tab_5);
        lw4_display->setObjectName(QString::fromUtf8("lw4_display"));
        lw4_display->setGeometry(QRect(220, 40, 611, 251));
        lw4_display->setFont(font1);
        label4_file = new QLabel(tab_5);
        label4_file->setObjectName(QString::fromUtf8("label4_file"));
        label4_file->setGeometry(QRect(320, 0, 511, 31));
        label4_file->setFrameShape(QFrame::Box);
        pb4_selfile = new QPushButton(tab_5);
        pb4_selfile->setObjectName(QString::fromUtf8("pb4_selfile"));
        pb4_selfile->setGeometry(QRect(100, 200, 111, 27));
        pb4_start = new QPushButton(tab_5);
        pb4_start->setObjectName(QString::fromUtf8("pb4_start"));
        pb4_start->setGeometry(QRect(100, 230, 111, 27));
        pb4_clear = new QPushButton(tab_5);
        pb4_clear->setObjectName(QString::fromUtf8("pb4_clear"));
        pb4_clear->setGeometry(QRect(170, 260, 41, 27));
        label_23 = new QLabel(tab_5);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(220, 10, 91, 16));
        groupBox_5 = new QGroupBox(tab_5);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 10, 191, 101));
        rb4_ram = new QRadioButton(groupBox_5);
        rb4_ram->setObjectName(QString::fromUtf8("rb4_ram"));
        rb4_ram->setGeometry(QRect(11, 21, 177, 19));
        rb4_i2c = new QRadioButton(groupBox_5);
        rb4_i2c->setObjectName(QString::fromUtf8("rb4_i2c"));
        rb4_i2c->setGeometry(QRect(11, 46, 177, 19));
        rb4_spi = new QRadioButton(groupBox_5);
        rb4_spi->setObjectName(QString::fromUtf8("rb4_spi"));
        rb4_spi->setGeometry(QRect(11, 71, 177, 19));
        tab2->addTab(tab_5, QString());
        tab1->addTab(tab_3, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QString::fromUtf8("tab_6"));
        groupBox_4 = new QGroupBox(tab_6);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(10, 20, 171, 171));
        rb3_ramdl = new QRadioButton(groupBox_4);
        rb3_ramdl->setObjectName(QString::fromUtf8("rb3_ramdl"));
        rb3_ramdl->setGeometry(QRect(10, 20, 161, 20));
        rb3_ramup = new QRadioButton(groupBox_4);
        rb3_ramup->setObjectName(QString::fromUtf8("rb3_ramup"));
        rb3_ramup->setGeometry(QRect(10, 40, 161, 20));
        rb3_eedl = new QRadioButton(groupBox_4);
        rb3_eedl->setObjectName(QString::fromUtf8("rb3_eedl"));
        rb3_eedl->setGeometry(QRect(10, 60, 151, 20));
        rb3_eeup = new QRadioButton(groupBox_4);
        rb3_eeup->setObjectName(QString::fromUtf8("rb3_eeup"));
        rb3_eeup->setGeometry(QRect(10, 80, 161, 20));
        rb3_getchip = new QRadioButton(groupBox_4);
        rb3_getchip->setObjectName(QString::fromUtf8("rb3_getchip"));
        rb3_getchip->setGeometry(QRect(10, 100, 171, 20));
        rb3_renum = new QRadioButton(groupBox_4);
        rb3_renum->setObjectName(QString::fromUtf8("rb3_renum"));
        rb3_renum->setGeometry(QRect(10, 120, 151, 20));
        rb3_custom = new QRadioButton(groupBox_4);
        rb3_custom->setObjectName(QString::fromUtf8("rb3_custom"));
        rb3_custom->setGeometry(QRect(10, 140, 111, 20));
        label_10 = new QLabel(tab_6);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(291, 31, 68, 16));
        label_11 = new QLabel(tab_6);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(190, 30, 91, 16));
        QFont font2;
        font2.setPointSize(9);
        label_11->setFont(font2);
        label_12 = new QLabel(tab_6);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(387, 31, 68, 16));
        label_13 = new QLabel(tab_6);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(470, 30, 68, 16));
        label_14 = new QLabel(tab_6);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(570, 30, 68, 16));
        le3_br = new QLineEdit(tab_6);
        le3_br->setObjectName(QString::fromUtf8("le3_br"));
        le3_br->setGeometry(QRect(290, 60, 61, 25));
        le3_bm = new QLineEdit(tab_6);
        le3_bm->setObjectName(QString::fromUtf8("le3_bm"));
        le3_bm->setGeometry(QRect(190, 60, 81, 25));
        gb_dir = new QGroupBox(tab_6);
        gb_dir->setObjectName(QString::fromUtf8("gb_dir"));
        gb_dir->setGeometry(QRect(190, 100, 71, 61));
        rb3_out = new QRadioButton(gb_dir);
        rb3_out->setObjectName(QString::fromUtf8("rb3_out"));
        rb3_out->setGeometry(QRect(0, 20, 61, 20));
        rb3_in = new QRadioButton(gb_dir);
        rb3_in->setObjectName(QString::fromUtf8("rb3_in"));
        rb3_in->setGeometry(QRect(0, 40, 61, 20));
        le3_wval = new QLineEdit(tab_6);
        le3_wval->setObjectName(QString::fromUtf8("le3_wval"));
        le3_wval->setGeometry(QRect(380, 60, 51, 25));
        le3_wind = new QLineEdit(tab_6);
        le3_wind->setObjectName(QString::fromUtf8("le3_wind"));
        le3_wind->setGeometry(QRect(470, 60, 61, 25));
        le3_wlen = new QLineEdit(tab_6);
        le3_wlen->setObjectName(QString::fromUtf8("le3_wlen"));
        le3_wlen->setGeometry(QRect(570, 60, 61, 25));
        le3_wlen->setMaxLength(3);
        label_15 = new QLabel(tab_6);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(290, 10, 81, 16));
        QFont font3;
        font3.setPointSize(8);
        label_15->setFont(font3);
        label_16 = new QLabel(tab_6);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(190, 10, 81, 16));
        label_16->setFont(font3);
        label_17 = new QLabel(tab_6);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(380, 10, 91, 16));
        label_17->setFont(font3);
        label_18 = new QLabel(tab_6);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(470, 10, 91, 16));
        label_18->setFont(font3);
        label_19 = new QLabel(tab_6);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(570, 10, 91, 16));
        label_19->setFont(font3);
        le3_out_hex = new QLineEdit(tab_6);
        le3_out_hex->setObjectName(QString::fromUtf8("le3_out_hex"));
        le3_out_hex->setGeometry(QRect(350, 170, 431, 25));
        le3_out_hex->setMaxLength(64);
        pb_execvc = new QPushButton(tab_6);
        pb_execvc->setObjectName(QString::fromUtf8("pb_execvc"));
        pb_execvc->setGeometry(QRect(700, 50, 141, 41));
        QFont font4;
        font4.setPointSize(11);
        pb_execvc->setFont(font4);
        pb3_selfile = new QPushButton(tab_6);
        pb3_selfile->setObjectName(QString::fromUtf8("pb3_selfile"));
        pb3_selfile->setGeometry(QRect(290, 110, 51, 27));
        lab3_selfile = new QLabel(tab_6);
        lab3_selfile->setObjectName(QString::fromUtf8("lab3_selfile"));
        lab3_selfile->setGeometry(QRect(350, 110, 431, 31));
        lab3_selfile->setFrameShape(QFrame::Box);
        label_26 = new QLabel(tab_6);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(350, 90, 251, 16));
        pb3_dl = new QPushButton(tab_6);
        pb3_dl->setObjectName(QString::fromUtf8("pb3_dl"));
        pb3_dl->setGeometry(QRect(790, 110, 71, 27));
        lw3 = new QListWidget(tab_6);
        lw3->setObjectName(QString::fromUtf8("lw3"));
        lw3->setGeometry(QRect(10, 240, 771, 161));
        lw3->setFont(font1);
        pb3 = new QPushButton(tab_6);
        pb3->setObjectName(QString::fromUtf8("pb3"));
        pb3->setGeometry(QRect(790, 370, 41, 27));
        label_22 = new QLabel(tab_6);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 220, 141, 16));
        le3_out_ascii = new QLineEdit(tab_6);
        le3_out_ascii->setObjectName(QString::fromUtf8("le3_out_ascii"));
        le3_out_ascii->setGeometry(QRect(350, 200, 431, 25));
        le3_out_ascii->setMaxLength(64);
        label_25 = new QLabel(tab_6);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(240, 170, 101, 16));
        label_30 = new QLabel(tab_6);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(240, 200, 101, 16));
        tab1->addTab(tab_6, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tabWidget = new QTabWidget(tab_2);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(0, 10, 861, 401));
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        cb6_out = new QComboBox(tab_7);
        cb6_out->setObjectName(QString::fromUtf8("cb6_out"));
        cb6_out->setGeometry(QRect(50, 30, 101, 25));
        cb6_in = new QComboBox(tab_7);
        cb6_in->setObjectName(QString::fromUtf8("cb6_in"));
        cb6_in->setGeometry(QRect(200, 30, 101, 25));
        groupBox_6 = new QGroupBox(tab_7);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(440, 20, 121, 81));
        rb6_constant = new QRadioButton(groupBox_6);
        rb6_constant->setObjectName(QString::fromUtf8("rb6_constant"));
        rb6_constant->setGeometry(QRect(10, 20, 106, 20));
        rb6_random = new QRadioButton(groupBox_6);
        rb6_random->setObjectName(QString::fromUtf8("rb6_random"));
        rb6_random->setGeometry(QRect(10, 40, 106, 20));
        rb6_inc = new QRadioButton(groupBox_6);
        rb6_inc->setObjectName(QString::fromUtf8("rb6_inc"));
        rb6_inc->setGeometry(QRect(10, 60, 121, 20));
        le6_value = new QLineEdit(tab_7);
        le6_value->setObjectName(QString::fromUtf8("le6_value"));
        le6_value->setGeometry(QRect(580, 40, 81, 25));
        le6_value->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_27 = new QLabel(tab_7);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(580, 20, 81, 16));
        le6_size = new QLineEdit(tab_7);
        le6_size->setObjectName(QString::fromUtf8("le6_size"));
        le6_size->setGeometry(QRect(670, 40, 81, 25));
        le6_size->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        cb6_loop = new QCheckBox(tab_7);
        cb6_loop->setObjectName(QString::fromUtf8("cb6_loop"));
        cb6_loop->setGeometry(QRect(160, 90, 101, 20));
        label_28 = new QLabel(tab_7);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(670, 20, 81, 16));
        lw6 = new QListWidget(tab_7);
        lw6->setObjectName(QString::fromUtf8("lw6"));
        lw6->setGeometry(QRect(440, 230, 411, 131));
        lw6->setFont(font1);
        pb6_clear = new QPushButton(tab_7);
        pb6_clear->setObjectName(QString::fromUtf8("pb6_clear"));
        pb6_clear->setGeometry(QRect(810, 200, 41, 27));
        pb6_send = new QPushButton(tab_7);
        pb6_send->setObjectName(QString::fromUtf8("pb6_send"));
        pb6_send->setGeometry(QRect(270, 90, 69, 27));
        pb6_rcv = new QPushButton(tab_7);
        pb6_rcv->setObjectName(QString::fromUtf8("pb6_rcv"));
        pb6_rcv->setGeometry(QRect(360, 90, 69, 27));
        label_31 = new QLabel(tab_7);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(50, 10, 101, 16));
        label_32 = new QLabel(tab_7);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(200, 10, 101, 16));
        groupBox_8 = new QGroupBox(tab_7);
        groupBox_8->setObjectName(QString::fromUtf8("groupBox_8"));
        groupBox_8->setGeometry(QRect(670, 70, 161, 121));
        label6_out = new QLabel(groupBox_8);
        label6_out->setObjectName(QString::fromUtf8("label6_out"));
        label6_out->setGeometry(QRect(80, 26, 71, 20));
        label6_out->setFrameShape(QFrame::Box);
        label6_out->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label6_in = new QLabel(groupBox_8);
        label6_in->setObjectName(QString::fromUtf8("label6_in"));
        label6_in->setGeometry(QRect(80, 56, 71, 20));
        label6_in->setFrameShape(QFrame::Box);
        label6_in->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_35 = new QLabel(groupBox_8);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 30, 59, 15));
        label_36 = new QLabel(groupBox_8);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(10, 60, 59, 15));
        label_24 = new QLabel(tab_7);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(20, 210, 91, 16));
        label_24->setFont(font3);
        le6_out_ascii = new QLineEdit(tab_7);
        le6_out_ascii->setObjectName(QString::fromUtf8("le6_out_ascii"));
        le6_out_ascii->setGeometry(QRect(180, 170, 431, 25));
        le6_out_ascii->setMaxLength(64);
        le6_out_hex = new QLineEdit(tab_7);
        le6_out_hex->setObjectName(QString::fromUtf8("le6_out_hex"));
        le6_out_hex->setGeometry(QRect(180, 140, 431, 25));
        le6_out_hex->setMaxLength(64);
        label_37 = new QLabel(tab_7);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(70, 170, 101, 16));
        label_29 = new QLabel(tab_7);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(70, 140, 101, 16));
        pb6_selout = new QPushButton(tab_7);
        pb6_selout->setObjectName(QString::fromUtf8("pb6_selout"));
        pb6_selout->setGeometry(QRect(120, 200, 51, 27));
        pb6_selin = new QPushButton(tab_7);
        pb6_selin->setObjectName(QString::fromUtf8("pb6_selin"));
        pb6_selin->setGeometry(QRect(440, 200, 51, 27));
        le6_outfile = new QLineEdit(tab_7);
        le6_outfile->setObjectName(QString::fromUtf8("le6_outfile"));
        le6_outfile->setGeometry(QRect(180, 200, 251, 25));
        le6_outfile->setReadOnly(true);
        le6_infile = new QLineEdit(tab_7);
        le6_infile->setObjectName(QString::fromUtf8("le6_infile"));
        le6_infile->setGeometry(QRect(500, 200, 241, 25));
        le6_infile->setReadOnly(true);
        lw6_out = new QListWidget(tab_7);
        lw6_out->setObjectName(QString::fromUtf8("lw6_out"));
        lw6_out->setGeometry(QRect(20, 230, 411, 131));
        lw6_out->setFont(font1);
        label_75 = new QLabel(tab_7);
        label_75->setObjectName(QString::fromUtf8("label_75"));
        label_75->setGeometry(QRect(750, 210, 41, 16));
        label_75->setFont(font3);
        pb6_clearhalt_out = new QPushButton(tab_7);
        pb6_clearhalt_out->setObjectName(QString::fromUtf8("pb6_clearhalt_out"));
        pb6_clearhalt_out->setGeometry(QRect(50, 60, 61, 21));
        pb6_clearhalt_out->setFont(font3);
        pb6_clearhalt_in = new QPushButton(tab_7);
        pb6_clearhalt_in->setObjectName(QString::fromUtf8("pb6_clearhalt_in"));
        pb6_clearhalt_in->setGeometry(QRect(240, 60, 61, 21));
        pb6_clearhalt_in->setFont(font3);
        tabWidget->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        pb7_clear = new QPushButton(tab_8);
        pb7_clear->setObjectName(QString::fromUtf8("pb7_clear"));
        pb7_clear->setGeometry(QRect(810, 200, 41, 27));
        pb7_rcv = new QPushButton(tab_8);
        pb7_rcv->setObjectName(QString::fromUtf8("pb7_rcv"));
        pb7_rcv->setGeometry(QRect(155, 150, 69, 27));
        cb7_in = new QComboBox(tab_8);
        cb7_in->setObjectName(QString::fromUtf8("cb7_in"));
        cb7_in->setGeometry(QRect(155, 50, 101, 25));
        pb7_send = new QPushButton(tab_8);
        pb7_send->setObjectName(QString::fromUtf8("pb7_send"));
        pb7_send->setGeometry(QRect(60, 150, 69, 27));
        cb7_out = new QComboBox(tab_8);
        cb7_out->setObjectName(QString::fromUtf8("cb7_out"));
        cb7_out->setGeometry(QRect(20, 50, 101, 25));
        label_71 = new QLabel(tab_8);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(20, 30, 101, 16));
        groupBox_16 = new QGroupBox(tab_8);
        groupBox_16->setObjectName(QString::fromUtf8("groupBox_16"));
        groupBox_16->setGeometry(QRect(495, 5, 306, 196));
        label_72 = new QLabel(groupBox_16);
        label_72->setObjectName(QString::fromUtf8("label_72"));
        label_72->setGeometry(QRect(150, 10, 59, 15));
        label_73 = new QLabel(groupBox_16);
        label_73->setObjectName(QString::fromUtf8("label_73"));
        label_73->setGeometry(QRect(230, 10, 59, 15));
        label7_totalout = new QLabel(groupBox_16);
        label7_totalout->setObjectName(QString::fromUtf8("label7_totalout"));
        label7_totalout->setGeometry(QRect(145, 70, 71, 20));
        label7_totalout->setFont(font1);
        label7_totalout->setFrameShape(QFrame::Box);
        label7_totalout->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_78 = new QLabel(groupBox_16);
        label_78->setObjectName(QString::fromUtf8("label_78"));
        label_78->setGeometry(QRect(15, 70, 121, 21));
        label_80 = new QLabel(groupBox_16);
        label_80->setObjectName(QString::fromUtf8("label_80"));
        label_80->setGeometry(QRect(10, 155, 81, 16));
        label7_totalin = new QLabel(groupBox_16);
        label7_totalin->setObjectName(QString::fromUtf8("label7_totalin"));
        label7_totalin->setGeometry(QRect(225, 70, 71, 20));
        label7_totalin->setFont(font1);
        label7_totalin->setFrameShape(QFrame::Box);
        label7_totalin->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_rateout = new QLabel(groupBox_16);
        label7_rateout->setObjectName(QString::fromUtf8("label7_rateout"));
        label7_rateout->setGeometry(QRect(145, 155, 71, 20));
        label7_rateout->setFont(font1);
        label7_rateout->setFrameShape(QFrame::Box);
        label7_rateout->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_ratein = new QLabel(groupBox_16);
        label7_ratein->setObjectName(QString::fromUtf8("label7_ratein"));
        label7_ratein->setGeometry(QRect(225, 155, 71, 20));
        label7_ratein->setFont(font1);
        label7_ratein->setFrameShape(QFrame::Box);
        label7_ratein->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_pktsize_out = new QLabel(groupBox_16);
        label7_pktsize_out->setObjectName(QString::fromUtf8("label7_pktsize_out"));
        label7_pktsize_out->setGeometry(QRect(145, 35, 71, 21));
        label7_pktsize_out->setFont(font1);
        label7_pktsize_out->setFrameShape(QFrame::Box);
        label7_pktsize_in = new QLabel(groupBox_16);
        label7_pktsize_in->setObjectName(QString::fromUtf8("label7_pktsize_in"));
        label7_pktsize_in->setGeometry(QRect(225, 35, 71, 21));
        label7_pktsize_in->setFont(font1);
        label7_pktsize_in->setFrameShape(QFrame::Box);
        label_70 = new QLabel(groupBox_16);
        label_70->setObjectName(QString::fromUtf8("label_70"));
        label_70->setGeometry(QRect(15, 35, 81, 20));
        label_70->setFont(font2);
        line_2 = new QFrame(groupBox_16);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(15, 55, 281, 16));
        line_2->setLineWidth(2);
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        label7_pktsin = new QLabel(groupBox_16);
        label7_pktsin->setObjectName(QString::fromUtf8("label7_pktsin"));
        label7_pktsin->setGeometry(QRect(225, 95, 71, 21));
        label7_pktsin->setFont(font1);
        label7_pktsin->setFrameShape(QFrame::Box);
        label7_pktsin->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_79 = new QLabel(groupBox_16);
        label_79->setObjectName(QString::fromUtf8("label_79"));
        label_79->setGeometry(QRect(15, 100, 126, 16));
        label7_pktsout = new QLabel(groupBox_16);
        label7_pktsout->setObjectName(QString::fromUtf8("label7_pktsout"));
        label7_pktsout->setGeometry(QRect(145, 95, 71, 20));
        label7_pktsout->setFont(font1);
        label7_pktsout->setFrameShape(QFrame::Box);
        label7_pktsout->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_81 = new QLabel(groupBox_16);
        label_81->setObjectName(QString::fromUtf8("label_81"));
        label_81->setGeometry(QRect(15, 130, 126, 16));
        label7_dropped_out = new QLabel(groupBox_16);
        label7_dropped_out->setObjectName(QString::fromUtf8("label7_dropped_out"));
        label7_dropped_out->setGeometry(QRect(145, 125, 71, 20));
        label7_dropped_out->setFont(font1);
        label7_dropped_out->setFrameShape(QFrame::Box);
        label7_dropped_out->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label7_dropped_in = new QLabel(groupBox_16);
        label7_dropped_in->setObjectName(QString::fromUtf8("label7_dropped_in"));
        label7_dropped_in->setGeometry(QRect(225, 125, 71, 20));
        label7_dropped_in->setFont(font1);
        label7_dropped_in->setFrameShape(QFrame::Box);
        label7_dropped_in->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_74 = new QLabel(tab_8);
        label_74->setObjectName(QString::fromUtf8("label_74"));
        label_74->setGeometry(QRect(155, 30, 101, 16));
        lw7_out = new QListWidget(tab_8);
        lw7_out->setObjectName(QString::fromUtf8("lw7_out"));
        lw7_out->setGeometry(QRect(20, 230, 411, 131));
        lw7_out->setFont(font1);
        lw7_in = new QListWidget(tab_8);
        lw7_in->setObjectName(QString::fromUtf8("lw7_in"));
        lw7_in->setGeometry(QRect(440, 230, 411, 131));
        lw7_in->setFont(font1);
        label_66 = new QLabel(tab_8);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(20, 210, 101, 16));
        label_66->setFont(font3);
        label_76 = new QLabel(tab_8);
        label_76->setObjectName(QString::fromUtf8("label_76"));
        label_76->setGeometry(QRect(440, 210, 91, 16));
        label_76->setFont(font3);
        label_77 = new QLabel(tab_8);
        label_77->setObjectName(QString::fromUtf8("label_77"));
        label_77->setGeometry(QRect(280, 30, 71, 16));
        cb7_numpkts = new QComboBox(tab_8);
        cb7_numpkts->setObjectName(QString::fromUtf8("cb7_numpkts"));
        cb7_numpkts->setGeometry(QRect(280, 50, 71, 25));
        cb7_numpkts->setFont(font1);
        groupBox_7 = new QGroupBox(tab_8);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(365, 125, 121, 80));
        rb7_enable = new QRadioButton(groupBox_7);
        rb7_enable->setObjectName(QString::fromUtf8("rb7_enable"));
        rb7_enable->setGeometry(QRect(10, 20, 106, 20));
        rb7_disable = new QRadioButton(groupBox_7);
        rb7_disable->setObjectName(QString::fromUtf8("rb7_disable"));
        rb7_disable->setGeometry(QRect(10, 50, 106, 20));
        pb7_clearhalt_in = new QPushButton(tab_8);
        pb7_clearhalt_in->setObjectName(QString::fromUtf8("pb7_clearhalt_in"));
        pb7_clearhalt_in->setGeometry(QRect(155, 80, 61, 21));
        pb7_clearhalt_in->setFont(font3);
        pb7_clearhalt_out = new QPushButton(tab_8);
        pb7_clearhalt_out->setObjectName(QString::fromUtf8("pb7_clearhalt_out"));
        pb7_clearhalt_out->setGeometry(QRect(60, 80, 61, 21));
        pb7_clearhalt_out->setFont(font3);
        tabWidget->addTab(tab_8, QString());
        tab1->addTab(tab_2, QString());
        label_2 = new QLabel(ControlCenter);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(310, 40, 101, 16));
        label_seldevice = new QLabel(ControlCenter);
        label_seldevice->setObjectName(QString::fromUtf8("label_seldevice"));
        label_seldevice->setGeometry(QRect(310, 60, 371, 21));
        label_seldevice->setFrameShape(QFrame::StyledPanel);
        label_seldevice->setLineWidth(2);
        label_seldevice->setMidLineWidth(0);
        listWidget = new QListWidget(ControlCenter);
        listWidget->setObjectName(QString::fromUtf8("listWidget"));
        listWidget->setGeometry(QRect(0, 60, 301, 81));
        label_8 = new QLabel(ControlCenter);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(311, 89, 121, 16));
        label_9 = new QLabel(ControlCenter);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(311, 118, 144, 16));
        label_if = new QLabel(ControlCenter);
        label_if->setObjectName(QString::fromUtf8("label_if"));
        label_if->setGeometry(QRect(460, 90, 21, 21));
        label_if->setAutoFillBackground(false);
        label_if->setFrameShape(QFrame::Box);
        label_aif = new QLabel(ControlCenter);
        label_aif->setObjectName(QString::fromUtf8("label_aif"));
        label_aif->setGeometry(QRect(460, 116, 21, 20));
        label_aif->setFrameShape(QFrame::Box);
        pb_reset = new QPushButton(ControlCenter);
        pb_reset->setObjectName(QString::fromUtf8("pb_reset"));
        pb_reset->setGeometry(QRect(750, 160, 111, 27));
        label_20 = new QLabel(ControlCenter);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(500, 90, 81, 21));
        label_devtype = new QLabel(ControlCenter);
        label_devtype->setObjectName(QString::fromUtf8("label_devtype"));
        label_devtype->setGeometry(QRect(590, 90, 41, 21));
        label_devtype->setFrameShape(QFrame::Box);
        QWidget::setTabOrder(rb3_custom, rb3_out);
        QWidget::setTabOrder(rb3_out, rb3_in);
        QWidget::setTabOrder(rb3_in, le3_bm);
        QWidget::setTabOrder(le3_bm, le3_br);
        QWidget::setTabOrder(le3_br, le3_wval);
        QWidget::setTabOrder(le3_wval, le3_wind);
        QWidget::setTabOrder(le3_wind, le3_wlen);
        QWidget::setTabOrder(le3_wlen, le3_out_ascii);
        QWidget::setTabOrder(le3_out_ascii, le3_out_hex);
        QWidget::setTabOrder(le3_out_hex, pb_execvc);
        QWidget::setTabOrder(pb_execvc, pb_setIFace);
        QWidget::setTabOrder(pb_setIFace, pb_setAltIf);
        QWidget::setTabOrder(pb_setAltIf, tab2);
        QWidget::setTabOrder(tab2, rb1_ram);
        QWidget::setTabOrder(rb1_ram, rb1_small);
        QWidget::setTabOrder(rb1_small, rb1_large);
        QWidget::setTabOrder(rb1_large, pb1_selfile);
        QWidget::setTabOrder(pb1_selfile, lw1_display);
        QWidget::setTabOrder(lw1_display, pb1_start);
        QWidget::setTabOrder(pb1_start, pb1_clear);
        QWidget::setTabOrder(pb1_clear, rb_internal);
        QWidget::setTabOrder(rb_internal, rb_external);
        QWidget::setTabOrder(rb_external, lw4_display);
        QWidget::setTabOrder(lw4_display, pb4_selfile);
        QWidget::setTabOrder(pb4_selfile, pb4_start);
        QWidget::setTabOrder(pb4_start, pb4_clear);
        QWidget::setTabOrder(pb4_clear, rb4_ram);
        QWidget::setTabOrder(rb4_ram, rb4_i2c);
        QWidget::setTabOrder(rb4_i2c, rb4_spi);
        QWidget::setTabOrder(rb4_spi, rb3_ramdl);
        QWidget::setTabOrder(rb3_ramdl, rb3_ramup);
        QWidget::setTabOrder(rb3_ramup, rb3_eedl);
        QWidget::setTabOrder(rb3_eedl, rb3_eeup);
        QWidget::setTabOrder(rb3_eeup, rb3_getchip);
        QWidget::setTabOrder(rb3_getchip, rb3_renum);
        QWidget::setTabOrder(rb3_renum, tab1);
        QWidget::setTabOrder(tab1, pb_clear);
        QWidget::setTabOrder(pb_clear, lw_desc);
        QWidget::setTabOrder(lw_desc, listWidget);
        QWidget::setTabOrder(listWidget, pb_reset);
        QWidget::setTabOrder(pb_reset, le_numIfaces);
        QWidget::setTabOrder(le_numIfaces, sb_selectIf);
        QWidget::setTabOrder(sb_selectIf, le_numAlt);
        QWidget::setTabOrder(le_numAlt, pb_kerneldetach);
        QWidget::setTabOrder(pb_kerneldetach, sb_selectAIf);
        QWidget::setTabOrder(sb_selectAIf, pb3_selfile);
        QWidget::setTabOrder(pb3_selfile, pb3_dl);
        QWidget::setTabOrder(pb3_dl, lw3);
        QWidget::setTabOrder(lw3, pb3);
        QWidget::setTabOrder(pb3, cb_kerneldriver);
        QWidget::setTabOrder(cb_kerneldriver, tabWidget);
        QWidget::setTabOrder(tabWidget, cb6_out);
        QWidget::setTabOrder(cb6_out, cb6_in);
        QWidget::setTabOrder(cb6_in, rb6_constant);
        QWidget::setTabOrder(rb6_constant, rb6_random);
        QWidget::setTabOrder(rb6_random, rb6_inc);
        QWidget::setTabOrder(rb6_inc, le6_value);
        QWidget::setTabOrder(le6_value, le6_size);
        QWidget::setTabOrder(le6_size, cb6_loop);
        QWidget::setTabOrder(cb6_loop, lw6);
        QWidget::setTabOrder(lw6, pb6_clear);
        QWidget::setTabOrder(pb6_clear, pb6_send);
        QWidget::setTabOrder(pb6_send, pb6_rcv);
        QWidget::setTabOrder(pb6_rcv, le6_out_ascii);
        QWidget::setTabOrder(le6_out_ascii, le6_out_hex);

        retranslateUi(ControlCenter);
        QObject::connect(pb_clear, SIGNAL(clicked()), lw_desc, SLOT(clear()));
        QObject::connect(listWidget, SIGNAL(currentTextChanged(QString)), label_seldevice, SLOT(setText(QString)));
        QObject::connect(pb1_clear, SIGNAL(clicked()), lw1_display, SLOT(clear()));
        QObject::connect(rb3_ramdl, SIGNAL(clicked()), rb3_out, SLOT(click()));
        QObject::connect(rb3_ramup, SIGNAL(clicked()), rb3_in, SLOT(click()));
        QObject::connect(rb3_eedl, SIGNAL(clicked()), rb3_out, SLOT(click()));
        QObject::connect(rb3_eeup, SIGNAL(clicked()), rb3_in, SLOT(click()));
        QObject::connect(rb3_getchip, SIGNAL(clicked()), rb3_out, SLOT(click()));
        QObject::connect(rb3_renum, SIGNAL(clicked()), rb3_out, SLOT(click()));
        QObject::connect(pb3, SIGNAL(clicked()), lw3, SLOT(clear()));
        QObject::connect(pb3, SIGNAL(clicked()), le3_out_hex, SLOT(clear()));
        QObject::connect(pb3, SIGNAL(clicked()), le3_out_ascii, SLOT(clear()));

        tab1->setCurrentIndex(0);
        tab2->setCurrentIndex(0);
        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(ControlCenter);
    } // setupUi

    void retranslateUi(QWidget *ControlCenter)
    {
        ControlCenter->setWindowTitle(QApplication::translate("ControlCenter", "CyUSB Suite for Linux", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("ControlCenter", "List of devices", 0, QApplication::UnicodeUTF8));
        pb_clear->setText(QApplication::translate("ControlCenter", "Clear", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("ControlCenter", "Interface", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("ControlCenter", "Num.of Ifaces", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("ControlCenter", "Select Iface", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("ControlCenter", "Num.of alternate interfaces", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("ControlCenter", "Select Alternate Interface", 0, QApplication::UnicodeUTF8));
        cb_kerneldriver->setText(QApplication::translate("ControlCenter", "Interface claimed", 0, QApplication::UnicodeUTF8));
        pb_kerneldetach->setText(QApplication::translate("ControlCenter", "Detach", 0, QApplication::UnicodeUTF8));
        pb_setIFace->setText(QApplication::translate("ControlCenter", "Set IFace", 0, QApplication::UnicodeUTF8));
        pb_setAltIf->setText(QApplication::translate("ControlCenter", "Set Alt.IF", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("ControlCenter", " If#    Alt    EP#    I/O    Type   MaxPS  Interval", 0, QApplication::UnicodeUTF8));
        tab1->setTabText(tab1->indexOf(tab), QApplication::translate("ControlCenter", "Descriptors", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("ControlCenter", "Download to ->", 0, QApplication::UnicodeUTF8));
        rb1_ram->setText(QApplication::translate("ControlCenter", "RAM", 0, QApplication::UnicodeUTF8));
        rb1_small->setText(QApplication::translate("ControlCenter", "Small EEPROM", 0, QApplication::UnicodeUTF8));
        rb1_large->setText(QApplication::translate("ControlCenter", "Large EEPROM (64KB)", 0, QApplication::UnicodeUTF8));
        pb1_selfile->setText(QApplication::translate("ControlCenter", "Select File", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("ControlCenter", "Selected File", 0, QApplication::UnicodeUTF8));
        label1_selfile->setText(QString());
        pb1_start->setText(QApplication::translate("ControlCenter", "Start Download", 0, QApplication::UnicodeUTF8));
        pb1_clear->setText(QApplication::translate("ControlCenter", "clear", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("ControlCenter", "Which RAM", 0, QApplication::UnicodeUTF8));
        rb_internal->setText(QApplication::translate("ControlCenter", "Internal", 0, QApplication::UnicodeUTF8));
        rb_external->setText(QApplication::translate("ControlCenter", "External", 0, QApplication::UnicodeUTF8));
        tab2->setTabText(tab2->indexOf(tab_4), QApplication::translate("ControlCenter", "FX2", 0, QApplication::UnicodeUTF8));
        label4_file->setText(QString());
        pb4_selfile->setText(QApplication::translate("ControlCenter", "Select File", 0, QApplication::UnicodeUTF8));
        pb4_start->setText(QApplication::translate("ControlCenter", "Start Download", 0, QApplication::UnicodeUTF8));
        pb4_clear->setText(QApplication::translate("ControlCenter", "clear", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("ControlCenter", "Selected File", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("ControlCenter", "Download to ->", 0, QApplication::UnicodeUTF8));
        rb4_ram->setText(QApplication::translate("ControlCenter", "RAM", 0, QApplication::UnicodeUTF8));
        rb4_i2c->setText(QApplication::translate("ControlCenter", "I2C EEPROM", 0, QApplication::UnicodeUTF8));
        rb4_spi->setText(QApplication::translate("ControlCenter", "SPI Flash", 0, QApplication::UnicodeUTF8));
        tab2->setTabText(tab2->indexOf(tab_5), QApplication::translate("ControlCenter", "FX3", 0, QApplication::UnicodeUTF8));
        tab1->setTabText(tab1->indexOf(tab_3), QApplication::translate("ControlCenter", "Program", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("ControlCenter", "Command", 0, QApplication::UnicodeUTF8));
        rb3_ramdl->setText(QApplication::translate("ControlCenter", "RAM (Ext.) Download", 0, QApplication::UnicodeUTF8));
        rb3_ramup->setText(QApplication::translate("ControlCenter", "RAM (Ext.) Upload", 0, QApplication::UnicodeUTF8));
        rb3_eedl->setText(QApplication::translate("ControlCenter", "EEPROM Download", 0, QApplication::UnicodeUTF8));
        rb3_eeup->setText(QApplication::translate("ControlCenter", "EEPROM Upload", 0, QApplication::UnicodeUTF8));
        rb3_getchip->setText(QApplication::translate("ControlCenter", "Get Chip Revision", 0, QApplication::UnicodeUTF8));
        rb3_renum->setText(QApplication::translate("ControlCenter", "Renumerate", 0, QApplication::UnicodeUTF8));
        rb3_custom->setText(QApplication::translate("ControlCenter", "Custom", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("ControlCenter", "bRequest", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("ControlCenter", "bmRequestType", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("ControlCenter", "wValue", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("ControlCenter", "wIndex", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("ControlCenter", "wLength", 0, QApplication::UnicodeUTF8));
        gb_dir->setTitle(QApplication::translate("ControlCenter", "Direction", 0, QApplication::UnicodeUTF8));
        rb3_out->setText(QApplication::translate("ControlCenter", "OUT", 0, QApplication::UnicodeUTF8));
        rb3_in->setText(QApplication::translate("ControlCenter", "IN", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("ControlCenter", "SETUPDAT[1]", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("ControlCenter", "SETUPDAT[0]", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("ControlCenter", "SETUPDAT[2,3]", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("ControlCenter", "SETUPDAT[4,5]", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("ControlCenter", "SETUPDAT[6,7]", 0, QApplication::UnicodeUTF8));
        pb_execvc->setText(QApplication::translate("ControlCenter", "Execute Command", 0, QApplication::UnicodeUTF8));
        pb3_selfile->setText(QApplication::translate("ControlCenter", "Select", 0, QApplication::UnicodeUTF8));
        lab3_selfile->setText(QString());
        label_26->setText(QApplication::translate("ControlCenter", "Select firmware file to download", 0, QApplication::UnicodeUTF8));
        pb3_dl->setText(QApplication::translate("ControlCenter", "Download", 0, QApplication::UnicodeUTF8));
        pb3->setText(QApplication::translate("ControlCenter", "clear", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("ControlCenter", "DATA-IN (hex / ascii)", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("ControlCenter", "Data-Out HEX", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("ControlCenter", "Data-Out ASCII", 0, QApplication::UnicodeUTF8));
        tab1->setTabText(tab1->indexOf(tab_6), QApplication::translate("ControlCenter", "Vendor Extensions", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("ControlCenter", "Data Pattern", 0, QApplication::UnicodeUTF8));
        rb6_constant->setText(QApplication::translate("ControlCenter", "Constant", 0, QApplication::UnicodeUTF8));
        rb6_random->setText(QApplication::translate("ControlCenter", "Random", 0, QApplication::UnicodeUTF8));
        rb6_inc->setText(QApplication::translate("ControlCenter", "Incrementing", 0, QApplication::UnicodeUTF8));
        le6_value->setInputMask(QApplication::translate("ControlCenter", "HH; ", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("ControlCenter", "Value (HEX)", 0, QApplication::UnicodeUTF8));
        cb6_loop->setText(QApplication::translate("ControlCenter", "Loopback", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("ControlCenter", "Size (bytes)", 0, QApplication::UnicodeUTF8));
        pb6_clear->setText(QApplication::translate("ControlCenter", "Clear", 0, QApplication::UnicodeUTF8));
        pb6_send->setText(QApplication::translate("ControlCenter", "SEND", 0, QApplication::UnicodeUTF8));
        pb6_rcv->setText(QApplication::translate("ControlCenter", "RECEIVE", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("ControlCenter", "Endpoint OUT", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("ControlCenter", "Endpoint IN", 0, QApplication::UnicodeUTF8));
        groupBox_8->setTitle(QApplication::translate("ControlCenter", "Transfer Statistics", 0, QApplication::UnicodeUTF8));
        label6_out->setText(QString());
        label6_in->setText(QString());
        label_35->setText(QApplication::translate("ControlCenter", "Data Out", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("ControlCenter", "Data In", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("ControlCenter", "Data Out", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("ControlCenter", "Data-Out ASCII", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("ControlCenter", "Data-Out HEX", 0, QApplication::UnicodeUTF8));
        pb6_selout->setText(QApplication::translate("ControlCenter", "out-file", 0, QApplication::UnicodeUTF8));
        pb6_selin->setText(QApplication::translate("ControlCenter", "in-file", 0, QApplication::UnicodeUTF8));
        label_75->setText(QApplication::translate("ControlCenter", "Data In", 0, QApplication::UnicodeUTF8));
        pb6_clearhalt_out->setText(QApplication::translate("ControlCenter", "Clear Halt", 0, QApplication::UnicodeUTF8));
        pb6_clearhalt_in->setText(QApplication::translate("ControlCenter", "Clear Halt", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_7), QApplication::translate("ControlCenter", "Bulk", 0, QApplication::UnicodeUTF8));
        pb7_clear->setText(QApplication::translate("ControlCenter", "Clear", 0, QApplication::UnicodeUTF8));
        pb7_rcv->setText(QApplication::translate("ControlCenter", "RECEIVE", 0, QApplication::UnicodeUTF8));
        pb7_send->setText(QApplication::translate("ControlCenter", "SEND", 0, QApplication::UnicodeUTF8));
        label_71->setText(QApplication::translate("ControlCenter", "Endpoint OUT", 0, QApplication::UnicodeUTF8));
        groupBox_16->setTitle(QApplication::translate("ControlCenter", "Transfer Statistics", 0, QApplication::UnicodeUTF8));
        label_72->setText(QApplication::translate("ControlCenter", "Data Out", 0, QApplication::UnicodeUTF8));
        label_73->setText(QApplication::translate("ControlCenter", "Data In", 0, QApplication::UnicodeUTF8));
        label7_totalout->setText(QString());
        label_78->setText(QApplication::translate("ControlCenter", "Total packets", 0, QApplication::UnicodeUTF8));
        label_80->setText(QApplication::translate("ControlCenter", " Rate (KB/s)", 0, QApplication::UnicodeUTF8));
        label7_totalin->setText(QString());
        label7_rateout->setText(QString());
        label7_ratein->setText(QString());
        label7_pktsize_out->setText(QString());
        label7_pktsize_in->setText(QString());
        label_70->setText(QApplication::translate("ControlCenter", "Max Pkt. Size", 0, QApplication::UnicodeUTF8));
        label7_pktsin->setText(QString());
        label_79->setText(QApplication::translate("ControlCenter", "Packets - Success", 0, QApplication::UnicodeUTF8));
        label7_pktsout->setText(QString());
        label_81->setText(QApplication::translate("ControlCenter", "Packets - Failed", 0, QApplication::UnicodeUTF8));
        label7_dropped_out->setText(QString());
        label7_dropped_in->setText(QString());
        label_74->setText(QApplication::translate("ControlCenter", "Endpoint IN", 0, QApplication::UnicodeUTF8));
        label_66->setText(QApplication::translate("ControlCenter", "Data Out", 0, QApplication::UnicodeUTF8));
        label_76->setText(QApplication::translate("ControlCenter", "Data In", 0, QApplication::UnicodeUTF8));
        label_77->setText(QApplication::translate("ControlCenter", "Num Pkts", 0, QApplication::UnicodeUTF8));
        groupBox_7->setTitle(QApplication::translate("ControlCenter", "Display Dump", 0, QApplication::UnicodeUTF8));
        rb7_enable->setText(QApplication::translate("ControlCenter", "Enable", 0, QApplication::UnicodeUTF8));
        rb7_disable->setText(QApplication::translate("ControlCenter", "Disable", 0, QApplication::UnicodeUTF8));
        pb7_clearhalt_in->setText(QApplication::translate("ControlCenter", "Clear Halt", 0, QApplication::UnicodeUTF8));
        pb7_clearhalt_out->setText(QApplication::translate("ControlCenter", "Clear Halt", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab_8), QApplication::translate("ControlCenter", "Isochronous", 0, QApplication::UnicodeUTF8));
        tab1->setTabText(tab1->indexOf(tab_2), QApplication::translate("ControlCenter", " Data Transfers", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("ControlCenter", "Selected device", 0, QApplication::UnicodeUTF8));
        label_seldevice->setText(QString());
        label_8->setText(QApplication::translate("ControlCenter", "Selected Interface", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("ControlCenter", "Selected Alt Interface", 0, QApplication::UnicodeUTF8));
        label_if->setText(QString());
        label_aif->setText(QString());
        pb_reset->setText(QApplication::translate("ControlCenter", "Reset Device", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("ControlCenter", "Device Type", 0, QApplication::UnicodeUTF8));
        label_devtype->setText(QApplication::translate("ControlCenter", "FX2", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class ControlCenter: public Ui_ControlCenter {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_CONTROLCENTER_H
